import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Noise } from "@/components/ui/noise";
import { SmoothScroll } from "@/components/smooth-scroll";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} antialiased`}
    >
      <body className="min-h-screen bg-[#ddddd8] text-[#141414] antialiased">
        <SmoothScroll>{children}</SmoothScroll>
        <Noise
          fullScreen
          className="pointer-events-none fixed inset-0 z-50 h-full w-full"
          patternAlpha={30}
          patternSize={250}
        />
      </body>
    </html>
  );
}
